### PR TITLE
feat: nix flake

### PR DESCRIPTION
**Pull request by CherryKitten**
TODO:
- Add https://github.com/NixOS/nixpkgs/pull/320522
- Add https://github.com/NixOS/nixpkgs/pull/320726
- Add instruction for building ISO to README.md

### CODE REVIEW

**Review by jcgruenhage — DISMISSED** [review]
Tried it out, found something that was never mentioned but is required: `ssss` is not available, but is required.

**Comment by lrsksr** [comment]
I don't know if that's a deliberate choice but I wasn't able to generate PGP keys with the `fos-new` script because the openpgp-ca package didn't include the patches that are mentioned in the Readme.

**Comment by CherryKitten** [comment]
> I don't know if that's a deliberate choice but I wasn't able to generate PGP keys with the `fos-new` script because the openpgp-ca package didn't include the patches that are mentioned in the Readme.

nope, that's actually something i forgot to do, i wanted to add the patches into the flake as soon as the package is upstream

I'll do that on monday

**Review by lrsksr — APPROVED** [review]

**Pull request merged**
